language: node_js
node_js:
  - 6.9.5
cache:
  yarn: true
  directories:
    - node_modules
dist: trusty
addons:
  chrome: stable
before_install:
  - yarn install
script:
  - yarn test
notifications:
  email:
  - k.bieri@4teamwork.ch, t.buchberger@4teamwork.ch
