language: node_js
node_js:
- 6.9.5
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn test
notifications:
  email:
  - k.bieri@4teamwork.ch, t.buchberger@4teamwork.ch
